-- MySQL Script generated by MySQL Workbench
-- jue 15 mar 2018 11:06:28 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type_classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_classroom` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`head_building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`head_building` (
  `person_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faculty` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`building` (
  `id` INT NOT NULL,
  `head_building_person_id` INT NOT NULL,
  `faculty_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_building_head_building1_idx` (`head_building_person_id` ASC),
  INDEX `fk_building_faculty1_idx` (`faculty_id` ASC),
  CONSTRAINT `fk_building_head_building1`
    FOREIGN KEY (`head_building_person_id`)
    REFERENCES `mydb`.`head_building` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_building_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `mydb`.`faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `person_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`deparment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`deparment` (
  `id` INT NOT NULL,
  `faculty_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `teacher_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_deparment_faculty1_idx` (`faculty_id` ASC),
  INDEX `fk_deparment_teacher1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_deparment_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `mydb`.`faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_deparment_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teacher` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classroom` (
  `id` INT NOT NULL,
  `type_classroom_id` INT NOT NULL,
  `building_id` INT NOT NULL,
  `deparment_id` INT NOT NULL,
  `capacity` SMALLINT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Classroom_Type_Classroom1_idx` (`type_classroom_id` ASC),
  INDEX `fk_classroom_building1_idx` (`building_id` ASC),
  INDEX `fk_classroom_deparment1_idx` (`deparment_id` ASC),
  CONSTRAINT `fk_Classroom_Type_Classroom1`
    FOREIGN KEY (`type_classroom_id`)
    REFERENCES `mydb`.`type_classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_building1`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`building` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_deparment1`
    FOREIGN KEY (`deparment_id`)
    REFERENCES `mydb`.`deparment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purpose_classroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purpose_classroom` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`external_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`external_person` (
  `id` INT NOT NULL,
  `e-mail` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request_alternative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request_alternative` (
  `id` INT NOT NULL,
  `request_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_request_alternatives_request1_idx` (`request_id` ASC),
  CONSTRAINT `fk_request_alternatives_request1`
    FOREIGN KEY (`request_id`)
    REFERENCES `mydb`.`request` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `external_person_id` INT NOT NULL,
  `purpose_classroom_id` INT NOT NULL,
  `type_classroom_id` INT NOT NULL,
  `request_date` DATETIME NULL,
  `state` VARCHAR(45) NULL,
  `accepted_alternatives_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Request_Teacher1_idx` (`teacher_id` ASC),
  INDEX `fk_request_purpose_classroom1_idx` (`purpose_classroom_id` ASC),
  INDEX `fk_request_type_classroom1_idx` (`type_classroom_id` ASC),
  INDEX `fk_request_external_person1_idx` (`external_person_id` ASC),
  INDEX `fk_request_request_alternatives1_idx` (`accepted_alternatives_id` ASC),
  CONSTRAINT `fk_Request_Teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`teacher` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_purpose_classroom1`
    FOREIGN KEY (`purpose_classroom_id`)
    REFERENCES `mydb`.`purpose_classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_type_classroom1`
    FOREIGN KEY (`type_classroom_id`)
    REFERENCES `mydb`.`type_classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_external_person1`
    FOREIGN KEY (`external_person_id`)
    REFERENCES `mydb`.`external_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_request_alternatives1`
    FOREIGN KEY (`accepted_alternatives_id`)
    REFERENCES `mydb`.`request_alternative` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `person_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `person_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reports` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `classroom_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_classroom1_idx` (`classroom_id` ASC),
  CONSTRAINT `fk_reports_classroom1`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `mydb`.`classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`, `subject_id`),
  INDEX `fk_group_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_group_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cyclic_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cyclic_schedule` (
  `id` VARCHAR(45) NOT NULL,
  `day` INT(3) NULL,
  `begin_at` TIME(3) NULL,
  `end_at` TIME(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classroom_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classroom_schedule` (
  `schema_id` VARCHAR(45) NOT NULL,
  `classroom_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `group_subject_id` INT NOT NULL,
  `cyclic_schedule_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`schema_id`, `cyclic_schedule_id`),
  INDEX `fk_classroom_has_schedule_classroom1_idx` (`classroom_id` ASC),
  INDEX `fk_schema_group1_idx` (`group_id` ASC, `group_subject_id` ASC),
  INDEX `fk_classroom_schedule_cyclic_schedule1_idx` (`cyclic_schedule_id` ASC),
  CONSTRAINT `fk_classroom_has_schedule_classroom1`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `mydb`.`classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schema_group1`
    FOREIGN KEY (`group_id` , `group_subject_id`)
    REFERENCES `mydb`.`group` (`id` , `subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_schedule_cyclic_schedule1`
    FOREIGN KEY (`cyclic_schedule_id`)
    REFERENCES `mydb`.`cyclic_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`opinion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`opinion` (
  `id` INT NOT NULL,
  `student_person_id` INT NOT NULL,
  `schema_schema_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Opinion_Student1_idx` (`student_person_id` ASC),
  INDEX `fk_opinion_schema1_idx` (`schema_schema_id` ASC),
  CONSTRAINT `fk_Opinion_Student1`
    FOREIGN KEY (`student_person_id`)
    REFERENCES `mydb`.`student` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opinion_schema1`
    FOREIGN KEY (`schema_schema_id`)
    REFERENCES `mydb`.`classroom_schedule` (`schema_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cyclic_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cyclic_request` (
  `id` INT NOT NULL,
  `request_alternatives_id` INT NOT NULL,
  `cyclic_schedule_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_request_request_alternatives1_idx` (`request_alternatives_id` ASC),
  INDEX `fk_cyclic_request_cyclic_schedule1_idx` (`cyclic_schedule_id` ASC),
  CONSTRAINT `fk_schedule_request_request_alternatives1`
    FOREIGN KEY (`request_alternatives_id`)
    REFERENCES `mydb`.`request_alternative` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cyclic_request_cyclic_schedule1`
    FOREIGN KEY (`cyclic_schedule_id`)
    REFERENCES `mydb`.`cyclic_schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`specific_`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`specific_` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `begin_at` TIME(3) NULL,
  `end_at` TIME(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`specific_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`specific_request` (
  `id` INT NOT NULL,
  `request_alternative_id` INT NOT NULL,
  `specific__id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_specific_request_request_alternative1_idx` (`request_alternative_id` ASC),
  INDEX `fk_specific_request_specific_1_idx` (`specific__id` ASC),
  CONSTRAINT `fk_specific_request_request_alternative1`
    FOREIGN KEY (`request_alternative_id`)
    REFERENCES `mydb`.`request_alternative` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_specific_request_specific_1`
    FOREIGN KEY (`specific__id`)
    REFERENCES `mydb`.`specific_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`classroom_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`classroom_event` (
  `id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `specific__id` INT NOT NULL,
  `classroom_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_classroom_event_event1_idx` (`event_id` ASC),
  INDEX `fk_classroom_event_specific_1_idx` (`specific__id` ASC),
  INDEX `fk_classroom_event_classroom1_idx` (`classroom_id` ASC),
  CONSTRAINT `fk_classroom_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_event_specific_1`
    FOREIGN KEY (`specific__id`)
    REFERENCES `mydb`.`specific_` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classroom_event_classroom1`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `mydb`.`classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
